### ISSUE TITLE
svg

### ISSUE THREAD

**Issue by David1016** [tfx2001/python-turtle-draw-svg#1]
**Can't draw this svg file.**

[tmg.txt](https://github.com/tfx2001/python-turtle-draw-svg/files/2108064/tmg.txt)

**Comment by David1016** [comment]
[a.txt](https://github.com/tfx2001/python-turtle-draw-svg/files/2108076/a.txt)

**Comment by tfx2001** [comment]
这两个文件？

**Comment by tfx2001** [comment]
**tmg.txt**虽说是SVG格式，但实质上只是把原来的图片用`base64`编码，并不是转成矢量图，所以这个不支持😓

**Comment by tfx2001** [comment]
程序已重新设计，参见[commit 79232669c987e7d23194b2c90c147aa449025f7c](https://github.com/tfx2001/python-turtle-draw-svg/commit/79232669c987e7d23194b2c90c147aa449025f7c)
