### ISSUE TITLE
attributeError:'NopeType'object has no attribute 'shape' Python 3.7

### ISSUE THREAD

**Issue by huyukai** [tfx2001/python-turtle-draw-svg#5]

**Comment by huyukai** [comment]
File "C:\Users\24215\Desktop\hope.py", line 499, in <module>
    if bitmap.shape[0] > GetSystemMetrics(1):
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by huyukai** [comment]
如果可以的话顺便问一下怎么直接画位图吖

**Comment by tfx2001** [comment]
你怎么运行的啊？

**Comment by tfx2001** [comment]
@huyukai 你运行的命令是什么啊

**Comment by tfx2001** [comment]
@huyukai 这个是你自己写的吧？

**Comment by huyukai** [comment]
不是啊。。。直接粘的分享出来的main.py

**Comment by tfx2001** [comment]
@huyukai 我的程序哪里有400多行啊……:sweat:
